'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { db } from '@/lib/firebase';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import {
    Save,
    X,
    Upload,
    Wand2,
    Loader2,
    ChevronLeft,
    Image as ImageIcon,
    AlertCircle,
    CheckCircle2,
    Monitor,
    Smartphone,
    Laptop,
    HardDrive,
    Box,
    DollarSign,
    BarChart3
} from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { Separator } from '@/components/ui/separator';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import toast from 'react-hot-toast';

// Categories Configuration
const CATEGORIES = [
    { id: 'laptops', name: 'Laptops', icon: <Laptop className="w-6 h-6" />, code: 'Computers/Laptops' },
    { id: 'desktops', name: 'Desktops', icon: <Monitor className="w-6 h-6" />, code: 'Computers/Desktop Computers' },
    { id: 'phones', name: 'Smartphones', icon: <Smartphone className="w-6 h-6" />, code: 'Phones/Smartphones' },
    { id: 'components', name: 'Components', icon: <HardDrive className="w-6 h-6" />, code: 'Computers/Components' },
    { id: 'accessories', name: 'Accessories', icon: <Box className="w-6 h-6" />, code: 'Electronics/Accessories' },
];

export default function NewProductOrPage() {
    const router = useRouter();
    const [loading, setLoading] = useState(false);
    const [aiLoading, setAiLoading] = useState(false);
    const [aiModalOpen, setAiModalOpen] = useState(false);
    const [aiPrompt, setAiPrompt] = useState('');
    const [activeTab, setActiveTab] = useState('details');

    // Form State
    const [formData, setFormData] = useState({
        title: '',
        description: '',
        category: '',
        brand: '',
        price: '',
        costPrice: '',
        compareAtPrice: '',
        sku: '',
        barcode: '',
        quantity: '1',
        status: 'active',
        condition: 'New',
        imageUrl: '',
        specs: {
            processor: '',
            ram: '',
            storage: '',
            screenSize: '',
            color: ''
        }
    });

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        if (name.startsWith('specs.')) {
            const specName = name.split('.')[1];
            setFormData(prev => ({
                ...prev,
                specs: { ...prev.specs, [specName]: value }
            }));
        } else {
            setFormData(prev => ({ ...prev, [name]: value }));
        }
    };

    const calculateMargin = () => {
        const price = parseFloat(formData.price) || 0;
        const cost = parseFloat(formData.costPrice) || 0;
        if (price === 0) return 0;
        return ((price - cost) / price * 100).toFixed(1);
    };

    const handleAIGenerate = async () => {
        if (!aiPrompt) return;
        setAiLoading(true);

        try {
            // Simulate AI delay for demo (Using the existing API structure if available would be better, but we mock for reliability in UI demo)
            // In real scenario: const response = await fetch('/api/ai/product', ...);

            await new Promise(resolve => setTimeout(resolve, 2000));

            // Mock AI Response Logic
            const mockResponse = {
                title: `Premium ${aiPrompt} - High Performance Edition`,
                description: `Experience the ultimate power with this ${aiPrompt}. Designed for professionals and enthusiasts alike, it features top-tier specifications and a sleek design.\n\nKey Features:\n- Ultra-fast processing\n- Crystal clear display\n- All-day battery life`,
                specs: {
                    processor: 'M3 Pro Chip',
                    ram: '16GB Unified Memory',
                    storage: '512GB SSD',
                    screenSize: '14-inch Liquid Retina',
                    color: 'Space Black'
                },
                price: '1299.00'
            };

            setFormData(prev => ({
                ...prev,
                title: mockResponse.title,
                description: mockResponse.description,
                price: mockResponse.price,
                specs: { ...prev.specs, ...mockResponse.specs }
            }));

            toast.success('Product details generated by AI!');
            setAiModalOpen(false);
        } catch (error) {
            toast.error('Failed to generate content');
        } finally {
            setAiLoading(false);
        }
    };

    const handleSubmit = async () => {
        if (!formData.title || !formData.price) {
            toast.error('Please fill in required fields (Title, Price)');
            return;
        }

        setLoading(true);
        try {
            const productData = {
                title: { en: formData.title },
                short_description: { en: formData.description },
                category_code: formData.category,
                brand: formData.brand,
                main_image_url: formData.imageUrl,
                offer: {
                    price: parseFloat(formData.price),
                    quantity: parseInt(formData.quantity),
                    sku: formData.sku,
                    state: formData.condition,
                },
                specifications: {
                    processor_type: formData.specs.processor,
                    ram_size: formData.specs.ram,
                    ssd_capacity: formData.specs.storage,
                    screen_size: formData.specs.screenSize,
                    color: formData.specs.color,
                },
                status: formData.status,
                createdAt: serverTimestamp(),
                updatedAt: serverTimestamp(),
            };

            await addDoc(collection(db, 'products'), productData);
            toast.success('Product created successfully!');
            router.push('/admin/products');
        } catch (error) {
            console.error(error);
            toast.error('Failed to save product');
        } finally {
            setLoading(false);
        }
    };

    const profitMargin = calculateMargin();

    return (
        <div className="max-w-6xl mx-auto pb-20">
            {/* Top Navigation Bar */}
            <div className="flex items-center justify-between mb-6 sticky top-0 bg-white/80 backdrop-blur z-10 py-4 border-b">
                <div className="flex items-center gap-4">
                    <Button variant="ghost" size="icon" onClick={() => router.back()}>
                        <ChevronLeft className="w-5 h-5" />
                    </Button>
                    <div>
                        <h1 className="text-2xl font-bold text-gray-900">Add Product</h1>
                        <div className="flex items-center gap-2 text-sm text-gray-500">
                            <Badge variant={formData.status === 'active' ? 'default' : 'secondary'} className="uppercase text-[10px]">
                                {formData.status}
                            </Badge>
                            <span>•</span>
                            <span>Unsaved Changes</span>
                        </div>
                    </div>
                </div>
                <div className="flex gap-3">
                    <Dialog open={aiModalOpen} onOpenChange={setAiModalOpen}>
                        <DialogTrigger asChild>
                            <Button variant="outline" className="bg-gradient-to-r from-indigo-50 to-purple-50 text-indigo-700 border-indigo-200 hover:border-indigo-300">
                                <Wand2 className="w-4 h-4 mr-2 text-indigo-500" />
                                AI Autofill
                            </Button>
                        </DialogTrigger>
                        <DialogContent>
                            <DialogHeader>
                                <DialogTitle className="flex items-center gap-2">
                                    <Wand2 className="w-5 h-5 text-indigo-500" />
                                    AI Product Assistant
                                </DialogTitle>
                            </DialogHeader>
                            <div className="space-y-4 py-4">
                                <p className="text-sm text-gray-500">
                                    Describe your product or paste raw specs, and our AI will automatically fill out the title, description, and technical details for you.
                                </p>
                                <Textarea
                                    placeholder="e.g. MacBook Pro M3 14 inch, 16gb ram, 1tb ssd, brand new condition..."
                                    rows={5}
                                    value={aiPrompt}
                                    onChange={(e) => setAiPrompt(e.target.value)}
                                />
                                <div className="flex justify-end gap-2">
                                    <Button variant="outline" onClick={() => setAiModalOpen(false)}>Cancel</Button>
                                    <Button
                                        onClick={handleAIGenerate}
                                        disabled={!aiPrompt || aiLoading}
                                        className="bg-indigo-600 hover:bg-indigo-700 text-white"
                                    >
                                        {aiLoading ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Wand2 className="w-4 h-4 mr-2" />}
                                        Generate Product
                                    </Button>
                                </div>
                            </div>
                        </DialogContent>
                    </Dialog>
                    <Button variant="outline" onClick={() => router.back()}>Discard</Button>
                    <Button onClick={handleSubmit} disabled={loading} className="bg-black text-white hover:bg-gray-800">
                        {loading ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Save className="w-4 h-4 mr-2" />}
                        Save Product
                    </Button>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Left Column (Main Info) */}
                <div className="lg:col-span-2 space-y-8">
                    {/* Basic Details */}
                    <Card className="p-6 space-y-6">
                        <div className="space-y-2">
                            <Label htmlFor="title" className="text-base font-semibold">Product Title</Label>
                            <Input
                                id="title"
                                name="title"
                                placeholder="e.g. MacBook Pro 14-inch M3 Max"
                                className="text-lg py-6"
                                value={formData.title}
                                onChange={handleInputChange}
                            />
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="description" className="text-base font-semibold">Description</Label>
                            <div className="border rounded-md focus-within:ring-2 focus-within:ring-ring">
                                <div className="border-b p-2 bg-gray-50 flex gap-2">
                                    <Button variant="ghost" size="sm" className="h-8">B</Button>
                                    <Button variant="ghost" size="sm" className="h-8">I</Button>
                                    <Button variant="ghost" size="sm" className="h-8">List</Button>
                                </div>
                                <Textarea
                                    id="description"
                                    name="description"
                                    placeholder="Detailed product description..."
                                    className="min-h-[200px] border-0 focus-visible:ring-0 resize-none"
                                    value={formData.description}
                                    onChange={handleInputChange}
                                />
                            </div>
                        </div>
                    </Card>

                    {/* Media */}
                    <Card className="p-6">
                        <h3 className="text-base font-semibold mb-4">Media</h3>
                        <div className="border-2 border-dashed border-gray-200 rounded-lg p-8 text-center hover:bg-gray-50 transition-colors cursor-pointer group">
                            {formData.imageUrl ? (
                                <div className="relative aspect-video w-full max-w-md mx-auto overflow-hidden rounded-lg">
                                    <img src={formData.imageUrl} alt="Preview" className="object-cover w-full h-full" />
                                    <Button
                                        variant="destructive"
                                        size="icon"
                                        className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity"
                                        onClick={(e) => { e.stopPropagation(); setFormData(p => ({ ...p, imageUrl: '' })); }}
                                    >
                                        <X className="w-4 h-4" />
                                    </Button>
                                </div>
                            ) : (
                                <div className="flex flex-col items-center">
                                    <div className="w-12 h-12 bg-blue-50 text-blue-500 rounded-full flex items-center justify-center mb-3">
                                        <Upload className="w-6 h-6" />
                                    </div>
                                    <p className="font-medium text-gray-900">Click to upload or drag and drop</p>
                                    <p className="text-sm text-gray-500 mb-4">SVG, PNG, JPG or GIF (max. 800x400px)</p>
                                    <div className="flex items-center w-full max-w-xs mx-auto">
                                        <Separator className="flex-1" />
                                        <span className="px-2 text-xs text-gray-400">OR</span>
                                        <Separator className="flex-1" />
                                    </div>
                                    <Input
                                        placeholder="Paste image URL here"
                                        className="mt-4 max-w-sm"
                                        name="imageUrl"
                                        value={formData.imageUrl}
                                        onChange={handleInputChange}
                                    />
                                </div>
                            )}
                        </div>
                    </Card>

                    {/* Specifications */}
                    <Card className="p-6">
                        <h3 className="text-base font-semibold mb-4">Specifications</h3>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label>Brand</Label>
                                <Input name="brand" value={formData.brand} onChange={handleInputChange} placeholder="e.g. Apple" />
                            </div>
                            <div className="space-y-2">
                                <Label>Processor</Label>
                                <Input name="specs.processor" value={formData.specs.processor} onChange={handleInputChange} placeholder="e.g. M3 Max" />
                            </div>
                            <div className="space-y-2">
                                <Label>RAM Size</Label>
                                <Input name="specs.ram" value={formData.specs.ram} onChange={handleInputChange} placeholder="e.g. 32GB" />
                            </div>
                            <div className="space-y-2">
                                <Label>Storage</Label>
                                <Input name="specs.storage" value={formData.specs.storage} onChange={handleInputChange} placeholder="e.g. 1TB SSD" />
                            </div>
                            <div className="space-y-2">
                                <Label>Screen Size</Label>
                                <Input name="specs.screenSize" value={formData.specs.screenSize} onChange={handleInputChange} placeholder="e.g. 14 inch" />
                            </div>
                            <div className="space-y-2">
                                <Label>Color</Label>
                                <Input name="specs.color" value={formData.specs.color} onChange={handleInputChange} placeholder="e.g. Space Black" />
                            </div>
                        </div>
                    </Card>
                </div>

                {/* Right Column (Organization & Price) */}
                <div className="space-y-8">
                    {/* Status */}
                    <Card className="p-6">
                        <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">Product Status</h3>
                        <div className="space-y-4">
                            <div className="flex items-center justify-between">
                                <Label htmlFor="status">Active</Label>
                                <Switch
                                    id="status"
                                    checked={formData.status === 'active'}
                                    onCheckedChange={(c) => setFormData(p => ({ ...p, status: c ? 'active' : 'draft' }))}
                                />
                            </div>
                            <Separator />
                            <div className="space-y-2">
                                <Label>Product Category</Label>
                                <select
                                    className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background"
                                    name="category"
                                    value={formData.category}
                                    onChange={handleInputChange}
                                >
                                    <option value="">Select Category...</option>
                                    {CATEGORIES.map(cat => (
                                        <option key={cat.id} value={cat.code}>{cat.name}</option>
                                    ))}
                                </select>
                            </div>
                            <div className="space-y-2">
                                <Label>Condition</Label>
                                <select
                                    className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background"
                                    name="condition"
                                    value={formData.condition}
                                    onChange={handleInputChange}
                                >
                                    <option value="New">Brand New</option>
                                    <option value="Open Box">Open Box</option>
                                    <option value="Used">Used</option>
                                    <option value="Refurbished">Refurbished</option>
                                </select>
                            </div>
                        </div>
                    </Card>

                    {/* Pricing */}
                    <Card className="p-6">
                        <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">Pricing</h3>
                        <div className="space-y-4">
                            <div className="space-y-2">
                                <Label>Price</Label>
                                <div className="relative">
                                    <DollarSign className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                                    <Input
                                        type="number"
                                        className="pl-9"
                                        name="price"
                                        placeholder="0.00"
                                        value={formData.price}
                                        onChange={handleInputChange}
                                    />
                                </div>
                            </div>
                            <div className="flex gap-4">
                                <div className="space-y-2 flex-1">
                                    <Label>Compare at</Label>
                                    <Input
                                        type="number"
                                        name="compareAtPrice"
                                        placeholder="0.00"
                                        value={formData.compareAtPrice}
                                        onChange={handleInputChange}
                                    />
                                </div>
                                <div className="space-y-2 flex-1">
                                    <Label>Cost per item</Label>
                                    <Input
                                        type="number"
                                        name="costPrice"
                                        placeholder="0.00"
                                        value={formData.costPrice}
                                        onChange={handleInputChange}
                                    />
                                </div>
                            </div>
                            {formData.price && formData.costPrice && (
                                <div className="flex items-center justify-between text-sm p-3 bg-gray-50 rounded-lg">
                                    <span className="text-gray-500">Margin</span>
                                    <span className={`font-semibold ${Number(profitMargin) > 20 ? 'text-green-600' : 'text-orange-600'}`}>
                                        {profitMargin}%
                                    </span>
                                </div>
                            )}
                        </div>
                    </Card>

                    {/* Inventory */}
                    <Card className="p-6">
                        <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">Inventory</h3>
                        <div className="space-y-4">
                            <div className="space-y-2">
                                <Label>SKU (Stock Keeping Unit)</Label>
                                <Input name="sku" value={formData.sku} onChange={handleInputChange} />
                            </div>
                            <div className="space-y-2">
                                <Label>Barcode (ISBN, UPC, GTIN)</Label>
                                <Input name="barcode" value={formData.barcode} onChange={handleInputChange} />
                            </div>
                            <div className="space-y-2">
                                <Label>Quantity</Label>
                                <Input type="number" name="quantity" value={formData.quantity} onChange={handleInputChange} />
                            </div>
                        </div>
                    </Card>
                </div>
            </div>
        </div>
    );
}
